name = "flashy-backend"
main = "worker.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "DB"
id = "8783881b9eba446b8511897c7d3f6538"

[observability.logs]
enabled = true
invocation_logs = true
